In [3]:
from multiprocessing import Pool
import os
import numpy as np

Let's make an input array: 

In [9]:
in_arr = np.random.rand(100).reshape([10,10])
in_arr

array([[0.7844556 , 0.3649571 , 0.79781585, 0.20578906, 0.30335325,
        0.58899879, 0.67576375, 0.96186546, 0.82353776, 0.52508893],
       [0.97788854, 0.03800302, 0.5611147 , 0.93147078, 0.47390391,
        0.62035283, 0.48421912, 0.80672832, 0.08457726, 0.12521426],
       [0.0752155 , 0.27875583, 0.6746412 , 0.89456011, 0.31638405,
        0.71535937, 0.07756498, 0.92817422, 0.79096172, 0.86469405],
       [0.33341638, 0.2692845 , 0.90382138, 0.13951796, 0.98074376,
        0.19230482, 0.41404012, 0.76488874, 0.85874205, 0.21618609],
       [0.02020815, 0.49924676, 0.37501254, 0.60865117, 0.60656878,
        0.84615153, 0.33697482, 0.27702848, 0.1244202 , 0.91221554],
       [0.72837377, 0.24786082, 0.58809446, 0.96994207, 0.03670259,
        0.02983731, 0.14787488, 0.15673298, 0.24410712, 0.91165143],
       [0.36995528, 0.89255593, 0.16694339, 0.72675647, 0.92729376,
        0.72715517, 0.90001788, 0.80106487, 0.74493911, 0.28954462],
       [0.8087736 , 0.25439306, 0.8779235

And a _zones_ array

In [22]:
zones = np.zeros(100).reshape([10,10])
zones[5:10,0:5] = 1
zones[5:10,5:10] = 2
zones[3:8,3:8] = 3

zones

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 3., 3., 3., 3., 0., 0.],
       [0., 0., 0., 3., 3., 3., 3., 3., 0., 0.],
       [1., 1., 1., 3., 3., 3., 3., 3., 2., 2.],
       [1., 1., 1., 3., 3., 3., 3., 3., 2., 2.],
       [1., 1., 1., 3., 3., 3., 3., 3., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.]])

Next, we'll try to run a (long) function on each zone and put the changed values back in the original array:

In [23]:
np.unique(zones)

array([0., 1., 2., 3.])

In [38]:
def split_by_zone(a,z):

    """Splits a by zones defined in z, and returns:
    - the list of unique values from z, and
    - the sub-array of a for each of these zones"""

    zone_ids = np.unique(z)
    results = list()

    for zone in zone_ids:
        results.append((zone,a[z == zone]))

    return results


In [39]:
split_by_zone(in_arr, zones)

[(0.0, array([0.7844556 , 0.3649571 , 0.79781585, 0.20578906, 0.30335325,
         0.58899879, 0.67576375, 0.96186546, 0.82353776, 0.52508893,
         0.97788854, 0.03800302, 0.5611147 , 0.93147078, 0.47390391,
         0.62035283, 0.48421912, 0.80672832, 0.08457726, 0.12521426,
         0.0752155 , 0.27875583, 0.6746412 , 0.89456011, 0.31638405,
         0.71535937, 0.07756498, 0.92817422, 0.79096172, 0.86469405,
         0.33341638, 0.2692845 , 0.90382138, 0.85874205, 0.21618609,
         0.02020815, 0.49924676, 0.37501254, 0.1244202 , 0.91221554])),
 (1.0, array([0.72837377, 0.24786082, 0.58809446, 0.36995528, 0.89255593,
         0.16694339, 0.8087736 , 0.25439306, 0.87792357, 0.21348864,
         0.08814286, 0.73944538, 0.34308804, 0.11124429, 0.14914927,
         0.49287089, 0.06062178, 0.39584176, 0.86848775])),
 (2.0, array([0.24410712, 0.91165143, 0.74493911, 0.28954462, 0.03235461,
         0.83904541, 0.08922471, 0.6060031 , 0.13504225, 0.89081239,
         0.12257763, 0.79